services:
  - type: web
    name: telegram-session-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: "8350139839:AAHKChyb6VhRtJYx8R4BKDttllh-AhbSPMM"
      - key: API_ID
        value: "25136703"
      - key: API_HASH
        value: "accfaf5ecd981c67e481328515c39f89"
